data:
  dataset-path: ./images  
  save-result-images: true
  logs-path: results/logs
  checkpoints-path: results/checkpoints
  image-size: 128
  batch-size: 32

model:
  lr: 4e-03
  timestep-embedding-dim: 256
  device: 'cpu'
  input-channels: 3
  epochs: 2

diffusion:
  steps: 1000
  beta_upper: 0.02
  beta_lower: 1e-4
  device: 'cpu'